using Changeset;
using Changeset.EntityFramework;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace Changeset.EntityFramework.Tests;

public class SqliteAccount
{
    public int Id { get; set; }
    public int TenantId { get; set; }
    public string Username { get; set; } = "";
    public string Email { get; set; } = "";
    public int? ProfileId { get; set; }
    public SqliteProfile? Profile { get; set; }
}

public class SqliteProfile
{
    public int Id { get; set; }
    public string Bio { get; set; } = "";
}

public class SqliteTestDbContext : DbContext
{
    public DbSet<SqliteAccount> Accounts => Set<SqliteAccount>();
    public DbSet<SqliteProfile> Profiles => Set<SqliteProfile>();

    public SqliteTestDbContext(DbContextOptions<SqliteTestDbContext> options)
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder) =>
        modelBuilder.Entity<SqliteAccount>(account =>
        {
            account.HasIndex(a => a.Email).IsUnique();
            account.HasIndex(a => new { a.TenantId, a.Username }).IsUnique();
        });
}

/// <summary>
/// Integration tests against a real relational provider (SQLite in-memory). Unlike the
/// InMemory provider, these exercise actual SQL translation of the uniqueness queries,
/// real unique indexes, and genuine <see cref="DbUpdateException"/> constraint violations.
/// </summary>
public class SqliteIntegrationTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly SqliteTestDbContext _db;

    public SqliteIntegrationTests()
    {
        // Keep the connection open for the fixture's lifetime: an in-memory SQLite
        // database lives exactly as long as the connection that created it.
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();
        var options = new DbContextOptionsBuilder<SqliteTestDbContext>()
            .UseSqlite(_connection)
            .Options;
        _db = new SqliteTestDbContext(options);
        _db.Database.EnsureCreated();
    }

    public void Dispose()
    {
        _db.Dispose();
        _connection.Dispose();
    }

    private SqliteAccount SeedAccount(
        int tenantId = 1, string username = "alice", string email = "alice@test.com")
    {
        var account = new SqliteAccount
        {
            TenantId = tenantId, Username = username, Email = email
        };
        _db.Accounts.Add(account);
        _db.SaveChanges();
        _db.ChangeTracker.Clear();
        return account;
    }

    [Fact]
    public async Task ApplyToAsync_Insert_PersistsRowAndAssignsDatabaseId()
    {
        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 1, ["Username"] = "alice", ["Email"] = "alice@test.com"
            },
            ["TenantId", "Username", "Email"]);

        var entity = await cs.ApplyToAsync(_db);

        Assert.True(entity.Id > 0); // key generated by the database
        _db.ChangeTracker.Clear();
        var stored = Assert.Single(_db.Accounts.AsNoTracking());
        Assert.Equal("alice@test.com", stored.Email);
        Assert.Equal("alice", stored.Username);
    }

    [Fact]
    public async Task ApplyToAsync_Update_SendsOnlyChangedColumnsToDatabase()
    {
        var seeded = SeedAccount(email: "old@test.com");

        // A detached copy of the row; Username here is stale relative to the database.
        var existing = new SqliteAccount
        {
            Id = seeded.Id, TenantId = 1, Username = "alice", Email = "old@test.com"
        };

        // Change Username out of band. If the update sent all columns, the stale
        // attached value ("alice") would overwrite it; a partial UPDATE must not.
        await _db.Database.ExecuteSqlAsync(
            $"UPDATE \"Accounts\" SET \"Username\" = 'renamed' WHERE \"Id\" = {seeded.Id}");

        var cs = Changeset<SqliteAccount>.Cast(existing,
            new Dictionary<string, object?> { ["Email"] = "new@test.com" },
            ["Email", "Username"]);

        await cs.ApplyToAsync(_db);

        _db.ChangeTracker.Clear();
        var stored = _db.Accounts.AsNoTracking().Single(a => a.Id == seeded.Id);
        Assert.Equal("new@test.com", stored.Email);
        Assert.Equal("renamed", stored.Username); // unchanged column was not sent
    }

    [Fact]
    public async Task ApplyToAsync_Insert_PersistsAssociation()
    {
        var cs = Changeset<SqliteAccount>.Cast(
                new Dictionary<string, object?>
                {
                    ["TenantId"] = 1,
                    ["Username"] = "alice",
                    ["Email"] = "alice@test.com",
                    ["Profile"] = new Dictionary<string, object?> { ["Bio"] = "Hi there" }
                },
                ["TenantId", "Username", "Email"])
            .CastAssoc<SqliteAccount, SqliteProfile>("Profile", ["Bio"]);

        await cs.ApplyToAsync(_db);

        _db.ChangeTracker.Clear();
        var stored = _db.Accounts.AsNoTracking()
            .Include(a => a.Profile)
            .Single();
        Assert.NotNull(stored.Profile);
        Assert.Equal("Hi there", stored.Profile.Bio);
        Assert.Equal(stored.Profile.Id, stored.ProfileId);
    }

    [Fact]
    public void ValidateUnique_Conflict_AddsError()
    {
        SeedAccount(email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?> { ["Email"] = "alice@test.com" },
            ["Email"]);

        var result = cs.ValidateUnique(a => a.Email, _db);
        Assert.False(result.IsValid);
        Assert.Equal("uniqueness", result.Errors[0].Code);
    }

    [Fact]
    public async Task ValidateUniqueAsync_NoConflict_Passes()
    {
        SeedAccount(email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?> { ["Email"] = "bob@test.com" },
            ["Email"]);

        var result = await cs.ValidateUniqueAsync(a => a.Email, _db);
        Assert.True(result.IsValid);
    }

    [Fact]
    public async Task ValidateUniqueAsync_Update_ExcludesCurrentRowByPrimaryKey_Passes()
    {
        var seeded = SeedAccount(email: "alice@test.com");

        // A stale detached copy: its Email differs from the stored row, so the cast
        // records a change whose value matches only the row being updated. The primary-key
        // exclusion must translate to SQL and keep it from counting as a conflict.
        var staleCopy = new SqliteAccount
        {
            Id = seeded.Id, TenantId = 1, Username = "alice", Email = "outdated@test.com"
        };
        var cs = Changeset<SqliteAccount>.Cast(staleCopy,
            new Dictionary<string, object?> { ["Email"] = "alice@test.com" },
            ["Email"]);

        var result = await cs.ValidateUniqueAsync(a => a.Email, _db);
        Assert.True(result.IsValid);
    }

    [Fact]
    public void ValidateUnique_Update_ConflictsWithOtherRow_AddsError()
    {
        var alice = SeedAccount(username: "alice", email: "alice@test.com");
        SeedAccount(username: "bob", email: "bob@test.com");

        var cs = Changeset<SqliteAccount>.Cast(alice,
            new Dictionary<string, object?> { ["Email"] = "bob@test.com" },
            ["Email"]);

        var result = cs.ValidateUnique("Email", _db);
        Assert.False(result.IsValid);
        Assert.Equal("uniqueness", result.Errors[0].Code);
    }

    [Fact]
    public async Task ValidateUniqueAsync_Composite_Conflict_AddsError()
    {
        SeedAccount(tenantId: 1, username: "alice");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 1, ["Username"] = "alice", ["Email"] = "other@test.com"
            },
            ["TenantId", "Username", "Email"]);

        var result = await cs.ValidateUniqueAsync(
            a => new { a.TenantId, a.Username }, _db);
        Assert.False(result.IsValid);
        Assert.Equal("TenantId", result.Errors[0].Field);
        Assert.Equal("uniqueness", result.Errors[0].Code);
    }

    [Fact]
    public void ValidateUnique_Composite_DifferentTenant_Passes()
    {
        SeedAccount(tenantId: 1, username: "alice");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 2, ["Username"] = "alice", ["Email"] = "other@test.com"
            },
            ["TenantId", "Username", "Email"]);

        var result = cs.ValidateUnique(["TenantId", "Username"], _db);
        Assert.True(result.IsValid);
    }

    [Fact]
    public void ValidateUnique_ScopeExcludesConflictingRow_Passes()
    {
        SeedAccount(tenantId: 1, email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?> { ["Email"] = "alice@test.com" },
            ["Email"]);

        var result = cs.ValidateUnique("Email", _db, scope: a => a.TenantId == 99);
        Assert.True(result.IsValid);
    }

    [Fact]
    public async Task ValidateUniqueAsync_ScopeIncludesConflictingRow_AddsError()
    {
        SeedAccount(tenantId: 1, email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?> { ["Email"] = "alice@test.com" },
            ["Email"]);

        var result = await cs.ValidateUniqueAsync(
            a => a.Email, _db, scope: a => a.TenantId == 1);
        Assert.False(result.IsValid);
        Assert.Equal("uniqueness", result.Errors[0].Code);
    }

    [Fact]
    public async Task TryApplyToAsync_UniqueConstraintViolation_MapsToChangesetError()
    {
        SeedAccount(email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 2, ["Username"] = "bob", ["Email"] = "alice@test.com"
            },
            ["TenantId", "Username", "Email"]);

        var result = await cs.TryApplyToAsync(_db, exception =>
            exception.InnerException is SqliteException { SqliteErrorCode: 19 } inner
            && inner.Message.Contains("Accounts.Email")
                ? ChangesetError.For("Email", "has already been taken", "uniqueness")
                : null);

        var invalid = Assert.IsType<ChangesetResult<SqliteAccount>.Invalid>(result);
        var error = Assert.Single(invalid.Errors);
        Assert.Equal("Email", error.Field);
        Assert.Equal("uniqueness", error.Code);
        Assert.Single(_db.Accounts.AsNoTracking()); // duplicate row was not persisted
    }

    [Fact]
    public async Task TryApplyToAsync_CompositeUniqueConstraintViolation_MapsToChangesetError()
    {
        SeedAccount(tenantId: 1, username: "alice", email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 1, ["Username"] = "alice", ["Email"] = "other@test.com"
            },
            ["TenantId", "Username", "Email"]);

        var result = await cs.TryApplyToAsync(_db, exception =>
            exception.InnerException is SqliteException { SqliteErrorCode: 19 } inner
            && inner.Message.Contains("Accounts.TenantId")
                ? ChangesetError.For("Username", "has already been taken", "uniqueness")
                : null);

        var invalid = Assert.IsType<ChangesetResult<SqliteAccount>.Invalid>(result);
        Assert.Equal("Username", Assert.Single(invalid.Errors).Field);
    }

    [Fact]
    public async Task TryApplyToAsync_UnmappedConstraintViolation_Rethrows()
    {
        SeedAccount(email: "alice@test.com");

        var cs = Changeset<SqliteAccount>.Cast(
            new Dictionary<string, object?>
            {
                ["TenantId"] = 2, ["Username"] = "bob", ["Email"] = "alice@test.com"
            },
            ["TenantId", "Username", "Email"]);

        await Assert.ThrowsAsync<DbUpdateException>(
            () => cs.TryApplyToAsync(_db, _ => null));
    }
}
