using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Changeset.Generators;

[Generator]
public class ChangesetGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Changeset.ChangesetTargetAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes decorated with [ChangesetTarget]
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetModelInfo(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(classDeclarations, static (spc, model) =>
        {
            var source = GenerateSource(model);
            var hintName = (model.Namespace is not null ? $"{model.Namespace}.{model.TypeName}" : model.TypeName)
                .Replace("::", ".");
            spc.AddSource($"{hintName}.ChangesetApplier.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ModelInfo? GetModelInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var properties = new List<PropertyInfo>();
        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is IPropertySymbol prop &&
                prop.DeclaredAccessibility == Accessibility.Public &&
                !prop.IsReadOnly &&
                !prop.IsStatic &&
                prop.SetMethod is not null)
            {
                properties.Add(new PropertyInfo(
                    prop.Name,
                    prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
            }
        }

        if (properties.Count == 0)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new ModelInfo(
            typeSymbol.Name,
            ns,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            properties.ToImmutableArray());
    }

    private static string GenerateSource(ModelInfo model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        var applierClass = $"{model.TypeName}ChangesetApplier";
        var fullType = model.FullName;

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // Generate the applier class
        sb.AppendLine($"internal sealed class {applierClass} : global::Changeset.IChangesetApplier<{fullType}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static readonly {applierClass} Instance = new();");
        sb.AppendLine();

        // ValidFields
        sb.AppendLine("    private static readonly HashSet<string> _validFields = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"        \"{prop.Name}\",");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public IReadOnlySet<string> ValidFields => _validFields;");
        sb.AppendLine();

        // Create
        sb.AppendLine($"    public {fullType} Create(IReadOnlyDictionary<string, object?> changes)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var target = new {fullType}();");
        sb.AppendLine("        SetProperties(target, changes);");
        sb.AppendLine("        return target;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Apply
        sb.AppendLine($"    public {fullType} Apply({fullType} source, IReadOnlyDictionary<string, object?> changes)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var target = new {fullType}();");
        // Copy all properties from source
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"        target.{prop.Name} = source.{prop.Name};");
        }
        sb.AppendLine("        SetProperties(target, changes);");
        sb.AppendLine("        return target;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SetProperties — the switch-based setter
        sb.AppendLine($"    private static void SetProperties({fullType} target, IReadOnlyDictionary<string, object?> changes)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var (field, value) in changes)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (field)");
        sb.AppendLine("            {");
        foreach (var prop in model.Properties)
        {
            sb.AppendLine($"                case \"{prop.Name}\":");
            sb.AppendLine($"                    target.{prop.Name} = ({prop.TypeFullName})value!;");
            sb.AppendLine("                    break;");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        sb.AppendLine();

        // Module initializer to register the applier
        sb.AppendLine($"internal static class {applierClass}Registrar");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::Changeset.ChangesetApplierRegistry.Register({applierClass}.Instance);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

internal class ModelInfo
{
    public string TypeName { get; }
    public string? Namespace { get; }
    public string FullName { get; }
    public ImmutableArray<PropertyInfo> Properties { get; }

    public ModelInfo(string typeName, string? ns, string fullName, ImmutableArray<PropertyInfo> properties)
    {
        TypeName = typeName;
        Namespace = ns;
        FullName = fullName;
        Properties = properties;
    }
}

internal class PropertyInfo
{
    public string Name { get; }
    public string TypeFullName { get; }

    public PropertyInfo(string name, string typeFullName)
    {
        Name = name;
        TypeFullName = typeFullName;
    }
}
