using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Changeset.Generators;

[Generator]
public class ChangesetGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Changeset.ChangesetTargetAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes and records decorated with [ChangesetTarget]
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetModelInfo(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        context.RegisterSourceOutput(classDeclarations, static (spc, model) =>
        {
            var source = GenerateSource(model);
            var hintName = (model.Namespace is not null ? $"{model.Namespace}.{model.TypeName}" : model.TypeName)
                .Replace("::", ".");
            spc.AddSource($"{hintName}.ChangesetApplier.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ModelInfo? GetModelInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var properties = new List<PropertyInfo>();
        var seen = new HashSet<string>();
        for (var type = typeSymbol; type is not null && type.SpecialType != SpecialType.System_Object; type = type.BaseType)
        {
            foreach (var member in type.GetMembers())
            {
                if (member is IPropertySymbol prop &&
                    prop.DeclaredAccessibility == Accessibility.Public &&
                    !prop.IsReadOnly &&
                    !prop.IsStatic &&
                    prop.SetMethod is not null &&
                    seen.Add(prop.Name))
                {
                    properties.Add(new PropertyInfo(
                        prop.Name,
                        prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                }
            }
        }

        if (properties.Count == 0)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new ModelInfo(
            typeSymbol.Name,
            ns,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            properties.ToImmutableArray());
    }

    private static string GenerateSource(ModelInfo model)
    {
        var applierClass = $"{model.TypeName}ChangesetApplier";
        var fullType = model.FullName;

        var namespaceDecl = model.Namespace is not null
            ? $"namespace {model.Namespace};\n\n"
            : "";

        var validFields = string.Join("\n",
            model.Properties.Select(p => $"        \"{p.Name}\","));

        var copyProps = string.Join("\n",
            model.Properties.Select(p => $"        target.{p.Name} = source.{p.Name};"));

        var switchCases = string.Join("\n",
            model.Properties.Select(p =>
                $"                case \"{p.Name}\":\n" +
                $"                    target.{p.Name} = ({p.TypeFullName})value!;\n" +
                $"                    break;"));

        return $$"""
            // <auto-generated />
            #nullable enable

            using System.Collections.Generic;
            using System.Runtime.CompilerServices;

            {{namespaceDecl}}internal sealed class {{applierClass}} : global::Changeset.IChangesetApplier<{{fullType}}>
            {
                public static readonly {{applierClass}} Instance = new();

                private static readonly HashSet<string> _validFields = new(System.StringComparer.Ordinal)
                {
            {{validFields}}
                };

                public IReadOnlySet<string> ValidFields => _validFields;

                public {{fullType}} Create(IReadOnlyDictionary<string, object?> changes)
                {
                    var target = new {{fullType}}();
                    SetProperties(target, changes);
                    return target;
                }

                public {{fullType}} Apply({{fullType}} source, IReadOnlyDictionary<string, object?> changes)
                {
                    var target = new {{fullType}}();
            {{copyProps}}
                    SetProperties(target, changes);
                    return target;
                }

                private static void SetProperties({{fullType}} target, IReadOnlyDictionary<string, object?> changes)
                {
                    foreach (var (field, value) in changes)
                    {
                        switch (field)
                        {
            {{switchCases}}
                        }
                    }
                }
            }

            internal static class {{applierClass}}Registrar
            {
                [ModuleInitializer]
                internal static void Register()
                {
                    global::Changeset.ChangesetApplierRegistry.Register({{applierClass}}.Instance);
                }
            }
            """;
    }
}

internal class ModelInfo
{
    public string TypeName { get; }
    public string? Namespace { get; }
    public string FullName { get; }
    public ImmutableArray<PropertyInfo> Properties { get; }

    public ModelInfo(string typeName, string? ns, string fullName, ImmutableArray<PropertyInfo> properties)
    {
        TypeName = typeName;
        Namespace = ns;
        FullName = fullName;
        Properties = properties;
    }
}

internal class PropertyInfo
{
    public string Name { get; }
    public string TypeFullName { get; }

    public PropertyInfo(string name, string typeFullName)
    {
        Name = name;
        TypeFullName = typeFullName;
    }
}
