#!/usr/bin/env python3
"""Generate LLM-oriented documentation from the canonical MkDocs sources."""

from __future__ import annotations

import argparse
import difflib
from dataclasses import dataclass
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


@dataclass(frozen=True)
class Page:
    title: str
    filename: str
    description: str
    section: str


PAGES = (
    Page("Getting Started", "getting-started.md", "Install the package and build complete create and update pipelines.", "Start here"),
    Page("The Changeset Lifecycle", "lifecycle.md", "Understand immutable state, insert/update semantics, and final outcomes.", "Core concepts"),
    Page("Casting", "casting.md", "Allowlist fields, coerce input types, and configure casting behavior.", "Core concepts"),
    Page("Validation", "validation.md", "Use built-in, custom, and asynchronous validators.", "Core concepts"),
    Page("Errors", "errors.md", "Inspect structured errors and map them to application responses.", "Core concepts"),
    Page("Applying Changes", "applying-changes.md", "Materialize valid inserts and updates and understand copy behavior.", "Core concepts"),
    Page("Associations", "associations.md", "Cast and validate nested input, including current materialization limits.", "Core concepts"),
    Page("EF Core & ASP.NET Core", "ef-core.md", "Persist changes, validate uniqueness, and create HTTP responses.", "Integrations"),
    Page("Source Generator", "source-generator.md", "Use generated appliers and string-field diagnostics.", "Integrations"),
    Page("Recipes", "recipes.md", "Copy complete patterns for common application workflows.", "Reference"),
    Page("API Reference", "api-reference.md", "Look up public types, members, overloads, and error codes.", "Reference"),
    Page("Troubleshooting", "troubleshooting.md", "Diagnose behavior by observable symptom.", "Reference"),
)

FULL_PAGES = (
    Page("Overview", "index.md", "Understand the purpose, pipeline, and package choices.", "Start here"),
    *PAGES,
)


def llms_index() -> str:
    lines = [
        "# Changeset.NET",
        "",
        "> An immutable Ecto-style cast, validate, inspect, and apply pipeline for untrusted input in C# and .NET 10.",
        "",
        "Changeset.NET uses explicit field allowlists, type coercion, composable validation,",
        "structured errors, and an explicit materialization step. The core package does not",
        "mutate a model during casting or validation.",
        "",
        "Important semantics: most validators inspect only values in `Changes`;",
        "`ValidateRequired` also rejects absent values. Core `ApplyChanges` creates a new",
        "object for updates, while EF Core `ApplyTo` mutates the tracked entity.",
    ]

    current_section = None
    for page in PAGES:
        if page.section != current_section:
            current_section = page.section
            lines.extend(("", f"## {current_section}", ""))
        target = page.filename.removesuffix(".md") + "/"
        lines.append(f"- [{page.title}]({target}): {page.description}")

    lines.extend(
        (
            "",
            "## Complete context",
            "",
            "- [Full documentation corpus](llms-full.txt): All canonical guides combined in reading order for retrieval or prompt context.",
            "",
        )
    )
    return "\n".join(lines)


def llms_full() -> str:
    parts = [
        "# Changeset.NET — Complete Documentation",
        "",
        "> Generated from the canonical files in `docs/`. Do not edit this file directly.",
        "",
        "This corpus is ordered from introductory concepts through integrations and",
        "reference material. A `Source` line identifies the canonical file for each page.",
    ]
    for page in FULL_PAGES:
        body = (DOCS / page.filename).read_text(encoding="utf-8").strip()
        parts.extend(("", "---", "", f"Source: `docs/{page.filename}`", "", body))
    parts.append("")
    return "\n".join(parts)


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    if check:
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(path),
            tofile=f"{path} (generated)",
            lineterm="",
        )
        print("\n".join(diff), file=sys.stderr)
        return False
    path.write_text(expected, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated files differ instead of writing them",
    )
    args = parser.parse_args()

    outputs = {
        DOCS / "llms.txt": llms_index(),
        DOCS / "llms-full.txt": llms_full(),
    }
    return 0 if all(write_or_check(path, text, args.check) for path, text in outputs.items()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
